---
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test
  - deploy

# Use merge request pipeline
workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

pages:
  stage: deploy
  image: docker.io/python:3.9.9-alpine
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  before_script:
    - apk add --no-cache git
    - pip install -r requirements.txt
  script:
    - mkdocs build --site-dir ./public
  artifacts:
    paths:
      - public/
