---
site_name: Game Development @ Faculty of Computer Science Universitas Indonesia
site_description: >-
  The website of Game Development course at the Faculty of Computer Science
  Universitas Indonesia.
site_author: Daya Adianto
copyright: Copyright &copy; 2024 Faculty of Computer Science Universitas Indonesia

repo_url: https://github.com/CSUI-Game-Development/CSUI-Game-Development.github.io
repo_name: GitHub
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      type: iso_datetime
      enable_creation_date: true
      fallback_to_build_date: true
  - print-site

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/index.md
    - Tutorial 1 - Game Design Workshop: tutorials/tutorial-1/README.md
    - Tutorial 2 - Introduction to Game Engine: tutorials/tutorial-2/README.md
    - Tutorial 3 - Introduction to Game Programming: tutorials/tutorial-3/README.md
    - Tutorial 4 - Basic 2D Level Design: tutorials/tutorial-4/README.md
    - Tutorial 5 - Assets Creation & Integration: tutorials/tutorial-5/README.md
    - Tutorial 6 - Menu & In-Game GUI: tutorials/tutorial-6/README.md
    - Tutorial 7 - Basic 3D Game Mechanics & Level Design: tutorials/tutorial-7/README.md
    - Tutorial 8 - Game Polishing & Balancing: tutorials/tutorial-8/README.md
  - Exam Issue Template: exam-issue-template.md
